Revert "This adds an Android apk for running tests on  the Java layer of PeerConnection."
This reverts r7732

Reason: Breaks compilation on Linux:
[813/818] LINK libjingle_media_unittest
FAILED: cd ../../talk; build/build_jar.sh /usr/lib/jvm/java-7-openjdk-amd64 ../out/Debug/libjingle_peerconnection_test.jar ../out/Debug/obj/talk/libjingle_peerconnection_test_jar.gen app/webrtc/javatests/src:../out/Debug/libjingle_peerconnection.jar:../third_party/junit/junit-4.11.jar app/webrtc/java/testcommon/src/org/webrtc/PeerConnectionTest.java app/webrtc/javatests/src/org/webrtc/PeerConnectionTestJava.java
build/build_jar.sh: Entering directory `/mnt/data/b/build/slave/linux64/build/src/talk'
app/webrtc/java/testcommon/src/org/webrtc/PeerConnectionTest.java:46:warning: [deprecation] Assert in junit.framework has been deprecated
import static junit.framework.Assert.*;
                             ^
app/webrtc/javatests/src/org/webrtc/PeerConnectionTestJava.java:36:error: cannot find symbol
  @Test
   ^
  symbol:   class Test
  location: class PeerConnectionTestJava
app/webrtc/javatests/src/org/webrtc/PeerConnectionTestJava.java:43:error: cannot find symbol
  @Test
   ^
  symbol:   class Test
  location: class PeerConnectionTestJava
2 errors
1 warning
ninja: build stopped: subcommand failed.

TBR=perkj@webrtc.org
BUG=

Review URL: https://webrtc-codereview.appspot.com/32169004

git-svn-id: http://webrtc.googlecode.com/svn@7733 4adac7df-926f-26a2-2b94-8c16560cd09d